### ISSUE TITLE
Optimize front-end for display on mobile devices

### ISSUE THREAD

**Issue by Coldwine** [MEDIGO/laika#114]
As an administrator I wan't to be able to manage feature flags on the go, in order to react to critical issues in production code.

The current front-end doesn't provide a sufficient UI for mobile usage, since it's only the desktop version scaled into the view port.

We should offer an optimized version of the UI for mobile usage.

**Comment by matchs** [comment]
Closed by [#114](https://github.com/Coldwine/laika/commit/4a892a98a97c54e26f8830bce50e3f0ded67cc12)
