### ISSUE TITLE
Add dedicated API for clients

### ISSUE THREAD

**Issue by baecher** [MEDIGO/laika#119]
Clients querying the flag configuration currently use the same API end point as the front end. This is fairly wasteful as clients only require a small subset of all data (boolean value for all flags in a given environment).

**Comment by eggman64** [comment]
This is linked to https://github.com/MEDIGO/laika/issues/128 and resolved with https://github.com/MEDIGO/laika/commit/3b1303907188175b9c79cf5383eaf5c00b1f59b8

Clients can now use `/api/features/:name/status/:env`
