### ISSUE TITLE
No error if address already in use

### ISSUE THREAD

**Issue by baecher** [MEDIGO/laika#124]
Reproduce: listen on port 8000 with something, then start Laika on port 8000.

Expected: Laika fails to start and says something like address is already in use.

Actual: Laika claims to be running on port 8000 as usual but in fact is not running because it couldn't allocate the port.

**Comment by dmigo** [comment]
This is a perfect candidate to tag it Hacktoberfest
[https://hacktoberfest.digitalocean.com/](Here you can find more info)

**Comment by hi-manshu-kumar** [comment]
@eggman64 @dmigo  I would like to work on this issue, Can I pick this up?

**Comment by Jo-IE** [comment]
Hi, I am interested in the recent Fullstack role at Medigo and would like to learn more by contributing. Could I have a go at this issue?

Thanks!

**Comment by utsavtiwary04** [comment]
@Jo-IE Please do :)
