### ISSUE TITLE
Unintuitive environments ordering in UI

### ISSUE THREAD

**Issue by ssimono** [MEDIGO/laika#95]
The order of environment in the UI is `Dev`, `Prod`, `Test` which doesn't match the usual workflow. It is error-prone and could lead to unintentional flag switch on production

![screenshot from 2017-08-10 14-30-26](https://user-images.githubusercontent.com/2179169/29170376-9b0967aa-7dd8-11e7-9bea-1fb046cd7452.png)

**Comment by alexyans** [comment]
Let's make it shuffle randomly.

**Comment by baecher** [comment]
Fixed in #107.
